use floor division in bytesToTest()
In Python 3, the "/" operator yields float, which causes:

    TypeError: 'float' object cannot be interpreted as an integer